services:
  - type: web
    name: todo-ctf
    env: node
    plan: free
    branch: main
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: FLAG
        sync: false
